title: QPA
description: Quantum Software Analysis Project â€” reproducible framework for analyzing quantum software patterns.
baseurl: ""
url: ""
theme: minima
markdown: kramdown
plugins: [jekyll-feed]
exclude: ["node_modules", "venv", ".venv"]
